spring.cloud.stream.bindings.input:
  destination: userClickRegions
  consumer:
    useNativeEncoding: true
spring.cloud.stream.kafka.binder.configuration.key:
  deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.cloud.stream.kafka.binder.configuration.value:
  deserializer: org.apache.kafka.common.serialization.LongDeserializer
